apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmapp.mysql.deployment.name" . }}
  labels:
    {{- include "helmapp.labels" . | nindent 4 }}
    tier: mysql
spec:
  replicas: {{ .Values.mysql.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "helmapp.selectorLabels" . | nindent 6 }}
      tier: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include "helmapp.propertiesHash" . }}
      labels:
        {{- include "helmapp.selectorLabels" . | nindent 8 }}
        tier: mysql
    spec:
      serviceAccountName: {{ include "helmapp.serviceAccountName" . }}
      containers:
        - name: {{ include "helmapp.mysql.container.name" . }}
          image: "{{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "helmapp.urlConfig.defaultName" . }}
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "helmapp.secrets.defaultName" . }}
                  key: secret
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.mysql.container.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmapp.mysql.service.name" . }}
  labels:
    {{- include "helmapp.labels" . | nindent 4 }}
    tier: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      protocol: TCP
      targetPort: 3306
      name: http
  selector:
    {{- include "helmapp.selectorLabels" . | nindent 4 }}
    tier: mysql

---

{{- if .Values.mysql.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helmapp.mysql.hpa.name" . }}
  labels:
    {{- include "helmapp.labels" . | nindent 4 }}
    tier: mysql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helmapp.mysql.deployment.name" . }}
  minReplicas: {{ .Values.mysql.hpa.minReplicas }}
  maxReplicas: {{ .Values.mysql.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.mysql.hpa.targetCPUUtilizationPercentage }}
{{- end -}}
