apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmapp.urlConfig.defaultName" . }}
  labels:
    {{- include "helmapp.labels" . | nindent 4 }}
data:
  SERVER_ORIGIN: "http://{{ include "helmapp.app.service.name" . }}:{{ .Values.app.service.port }}/"
